name: Tests

on:
  pull_request:
    branches: [ main, rc/*, feat/* ]
    types: [ opened, ready_for_review ]
  push:
  workflow_dispatch:

jobs:
  test:
    name: Unit
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20.7
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.7
        id: go

      - name: Check out code
        uses: actions/checkout@v3

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
      - name: Unit tests
        run: make test
